{
    "openapi": "3.0.3",
    "info": {
        "title": "Documentation",
        "version": "1.0"
    },
    "components": {
        "securitySchemes": {
            "api_key": {
                "name": "Authorization",
                "type": "apiKey",
                "in": "header"
            }
        }
    },
    "servers": [
        {
        "url": "/"
        }
    ],
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "tags": ["Авторизация"],
                "summary": "Авторизация для админки",
                "description": "",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "example": {
                                "login": "string",
                                "password": "string"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Успешно",
                        "content": {
                            "application/json": {
                                "example": {
                                    "token": "string",
                                    "id": 0
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/files/list": {
            "get": {
                "security": [{ "api_key": [] }],
                "tags": [ "Файловая система" ],
                "summary": "Список загруженных файлов",
                "parameters": [
                    { "name": "name", "in": "query", "required": false, "description": "Поиск по названию файла" },
                    { "name": "place", "in": "query", "required": false, "description": "Тип загрузки", "schema": { "enum": [ "images", "document" ] } }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "example": {
                                    "items": [
                                        {
                                            "id": 0,
                                            "src": "string",
                                            "place": "string"
                                        }
                                    ],
                                    "meta": {
                                        "size": 0,
                                        "lastpage": 0,
                                        "perpage": 0,
                                        "page": 0
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/files/upload/images": {
            "post": {
                "security": [{ "api_key": [] }],
                "tags": [ "Файловая система" ],
                "summary": "Загрузка изображений",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "file_1": { "type": "string", "format": "binary" },
                                    "file_2": { "type": "string", "format": "binary" }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "example": { "message": "ok" }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/files/upload/documents": {
            "post": {
                "security": [{ "api_key": [] }],
                "tags": [ "Файловая система" ],
                "summary": "Загрузка документов",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "file_1": { "type": "string", "format": "binary" },
                                    "file_2": { "type": "string", "format": "binary" }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "example": { "message": "ok" }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/repressed": {
            "get": {
                "tags": ["Репрессированные"],
                "summary": "Получить всё (Для сайта и админки)",
                "security": [{ "api_key": [] }],
                "parameters": [
                    { "name": "Accept-Language", "in": "header", "required": true, "description": "Язык", "schema": { "enum": [ "kk", "ru" ] } },
                    { "name": "page", "in": "query", "schema": { "default": 0, "type": "string" } },
                    { "name": "perpage", "in": "query", "schema": { "default": 15, "type": "string" } },
                    { "name": "sort", "in": "query", "schema": { "type": "string", "enum": [ "-id", "id", "-created_at", "created_at", "fio", "-fio", "slug", "-slug" ]} },
                    { "name": "fio", "in": "query", "description": "Поиск по названию", "schema": { "type": "string" } },
                    { "name": "content", "in": "query", "description": "Поиск по контенту", "schema": { "type": "string" } },
                    { "name": "created_at", "in": "query", "schema": { "type": "string" } }
                ],
                "responses": {
                    "200": {
                        "description": "Успешно",
                        "content": {
                            "application/json": {
                                "example": {
                                    "items": [{
                                        "id": 0,
                                        "slug": "string",
                                        "fio": "string",
                                        "birthday_year": 0,
                                        "death_year": 0,
                                        "content_ru": "string",
                                        "content_kk": "string",
                                        "content_en": "string",
                                        "delete": 0,
                                        "created_at": "string",
                                        "updated_at": "string",
                                        "content": "string",
                                        "author": {
                                            "id": 0,
                                            "name": "string",
                                            "email": "string"
                                        }
                                    }],
                                    "meta": {
                                        "size": 0,
                                        "perpage": 0,
                                        "page": 0
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": ["Репрессированные"],
                "summary": "Создать",
                "security": [{ "api_key": [] }],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "fio": { "type": "string" },
                                    "content_ru": { "type": "string" },
                                    "content_kk": { "type": "string" },
                                    "content_en": { "type": "string" },
                                    "birthday_year": { "type": "string" },
                                    "death_year": { "type": "string" }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Создано",
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Created"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/repressed/{slug}": {
            "get": {
                "tags": ["Репрессированные"],
                "summary": "Получить",
                "description": "Два режима работы: С авторизацией (больше информации), и без авторизации",
                "parameters": [
                    { "name": "Accept-Language", "in": "header", "required": true, "description": "Язык", "schema": { "enum": [ "kk", "ru" ] } },
                    { "name": "slug", "required": true, "description": "Получить статью по slug-у", "in": "path", "schema": { "type": "string"}}
                ],
                "responses": {
                    "200": {
                        "description": "Один элемент",
                        "content": {
                            "application/json": {
                                "example": {
                                    "id": 0,
                                    "slug": "string",
                                    "fio": "string",
                                    "birthday_year": 0,
                                    "death_year": 0,
                                    "content_ru": "string",
                                    "content_kk": "string",
                                    "content_en": "string",
                                    "delete": 0,
                                    "created_at": "string",
                                    "updated_at": "string",
                                    "content": "string",
                                    "author": {
                                        "id": 0,
                                        "name": "string",
                                        "email": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": ["Репрессированные"],
                "summary": "Обновить",
                "description": "Обновить статью на сайте. Тело `multipart/form-data`",
                "security": [{ "api_key": [] }],
                "parameters": [
                    { "name": "slug", "required": true, "description": "Получить статью по slug-у", "in": "path", "schema": { "type": "string" }}
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "fio": { "type": "string" },
                                    "content_ru": { "type": "string" },
                                    "content_kk": { "type": "string" },
                                    "content_en": { "type": "string" },
                                    "birthday_year": { "type": "string" },
                                    "death_year": { "type": "string" }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "202": {
                        "description": "Обновлено",
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Updated"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/repressed/{id}": {
            "delete": {
                "tags": ["Репрессированные"],
                "summary": "Архивировать",
                "description": "",
                "security": [{ "api_key": [] }],
                "parameters": [
                    { "name": "id", "required": true, "in": "path", "schema": { "type": "string" }}
                ],
                "responses": {
                    "202": {
                        "description": "",
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Ok, record <id> delete"
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "tags": ["Репрессированные"],
                "summary": "Восстановить",
                "description": "",
                "security": [{ "api_key": [] }],
                "parameters": [
                    { "name": "id", "required": true, "in": "path", "schema": { "type": "string" }}
                ],
                "responses": {
                    "202": {
                        "description": "",
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Ok, record <id> revert"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/post": {
            "get": {
                "tags": ["Статьи"],
                "summary": "Получить все статьи (Для сайта и админки)",
                "description": "Два режима работы: С авторизацией (отключено кэширование), и без авторизации",
                "security": [{ "api_key": [] }],
                "parameters": [
                    { "name": "Accept-Language", "in": "header", "required": true, "description": "Язык", "schema": { "enum": [ "kk", "ru" ] } },
                    { "name": "page", "in": "query", "schema": { "default": 0, "type": "string" } },
                    { "name": "perpage", "in": "query", "schema": { "default": 15, "type": "string" } },
                    { "name": "sort", "in": "query", "schema": { "type": "string", "enum": [ "-id", "id", "-created_at", "created_at", "title_ru", "-title_ru", "slug", "-slug" ]} },
                    { "name": "tag", "in": "query", "description": "Фильтр тэгов, в скобках указывается index из массива тэгов в поиске", "schema": { "type": "array" } },
                    { "name": "title", "in": "query", "description": "Поиск по названию", "schema": { "type": "string" } },
                    { "name": "content", "in": "query", "description": "Поиск по контенту", "schema": { "type": "string" } },
                    { "name": "created_at", "in": "query", "schema": { "type": "string" } }
                ],
                "responses": {
                    "200": {
                        "description": "Успешно",
                        "content": {
                            "application/json": {
                                "example": {
                                    "items": [{
                                        "id": 0,
                                        "slug": "string",
                                        "title_ru": "string",
                                        "content_ru": "string",
                                        "tags": [
                                            "string"
                                        ],
                                        "created_at": "string",
                                        "updated_at": "string",
                                        "imgsrc": "string",
                                        "delete": 0,
                                        "title_kk": "string",
                                        "content_kk": "string",
                                        "title": "string",
                                        "content": "string",
                                        "author": {
                                            "id": 0,
                                            "name": "string",
                                            "email": "string"
                                        }
                                    }],
                                    "meta": {
                                        "size": 0,
                                        "perpage": 0,
                                        "page": 0
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": ["Статьи"],
                "summary": "Создать статью",
                "description": "Создаёт статью для сайта. Тело `multipart/form-data`",
                "security": [{ "api_key": [] }],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "title_ru": { "type": "string" },
                                    "title_kk": { "type": "string" },
                                    "title_en": { "type": "string" },
                                    "content_ru": { "type": "string" },
                                    "content_kk": { "type": "string" },
                                    "content_en": { "type": "string" },
                                    "tags": { "type": "array", "items": { "type": "string" } },
                                    "photo": { "type": "string", "format": "binary" }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Создано",
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Created"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/post/{slug}": {
            "get": {
                "tags": ["Статьи"],
                "summary": "Получить статью",
                "description": "Два режима работы: С авторизацией (больше информации), и без авторизации",
                "parameters": [
                    { "name": "Accept-Language", "in": "header", "required": true, "description": "Язык", "schema": { "enum": [ "kk", "ru" ] } },
                    { "name": "slug", "required": true, "description": "Получить статью по slug-у", "in": "path", "schema": { "type": "string"}}
                ],
                "responses": {
                    "200": {
                        "description": "Один элемент",
                        "content": {
                            "application/json": {
                                "example": {
                                    "id": 0,
                                    "slug": "string",
                                    "title_ru": "string",
                                    "content_ru": "string",
                                    "tags": [
                                        "string"
                                    ],
                                    "created_at": "string",
                                    "updated_at": "string",
                                    "imgsrc": "string",
                                    "delete": 0,
                                    "title_kk": "string",
                                    "content_kk": "string",
                                    "title": "string",
                                    "content": "string",
                                    "author": {
                                        "id": 0,
                                        "name": "string",
                                        "email": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": ["Статьи"],
                "summary": "Обновить статью",
                "description": "Обновить статью на сайте. Тело `multipart/form-data`",
                "security": [{ "api_key": [] }],
                "parameters": [
                    { "name": "slug", "required": true, "description": "Получить статью по slug-у", "in": "path", "schema": { "type": "string" }}
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "title_ru": { "type": "string" },
                                    "title_kk": { "type": "string" },
                                    "title_en": { "type": "string" },
                                    "content_ru": { "type": "string" },
                                    "content_kk": { "type": "string" },
                                    "content_en": { "type": "string" },
                                    "tags": { "type": "array", "items": { "type": "string" } },
                                    "photo": { "type": "string", "format": "binary" }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "202": {
                        "description": "Обновлено",
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Updated"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/post/{id}": {
            "delete": {
                "tags": ["Статьи"],
                "summary": "Архивировать статью",
                "description": "",
                "security": [{ "api_key": [] }],
                "parameters": [
                    { "name": "id", "required": true, "in": "path", "schema": { "type": "string" }}
                ],
                "responses": {
                    "202": {
                        "description": "",
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Ok, post <id> delete"
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "tags": ["Статьи"],
                "summary": "Восстановить статью",
                "description": "",
                "security": [{ "api_key": [] }],
                "parameters": [
                    { "name": "id", "required": true, "in": "path", "schema": { "type": "string" }}
                ],
                "responses": {
                    "202": {
                        "description": "",
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Ok, post <id> revert"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/event": {
            "get": {
                "tags": ["Мероприятия"],
                "summary": "Получить все мероприятия (Для сайта и админки)",
                "description": "Два режима работы: С авторизацией Тостая версия, и без авторизации Тонкая версия",
                "security": [{ "api_key": [] }],
                "parameters": [
                    { "name": "Accept-Language", "in": "header", "required": true, "description": "Язык", "schema": { "enum": [ "kk", "ru" ] } },
                    { "name": "page", "in": "query", "schema": { "default": 0, "type": "string" } },
                    { "name": "perpage", "in": "query", "schema": { "default": 15, "type": "string" } },
                    { "name": "sort", "in": "query", "schema": { "type": "string", "enum": [ "-id", "id", "-created_at", "created_at", "title_ru", "-title_ru", "slug", "-slug" ]} },
                    { "name": "tag", "in": "query", "description": "Фильтр тэгов, в скобках указывается index из массива тэгов в поиске", "schema": { "type": "array" } },
                    { "name": "title", "in": "query", "description": "Поиск по названию", "schema": { "type": "string" } },
                    { "name": "content", "in": "query", "description": "Поиск по контенту", "schema": { "type": "string" } },
                    { "name": "created_at", "in": "query", "schema": { "type": "string" } },
                    { "name": "mode", "in": "query", "description": "Выбор данных (Актуально/История)", "schema": { "enum": [ "all", "actual", "history" ] } }
                ],
                "responses": {
                    "200": {
                        "description": "Успешно",
                        "content": {
                            "application/json": {
                                "example": {
                                    "items": [{
                                        "id": 0,
                                        "slug": "string",
                                        "title_ru": "string",
                                        "title_kk": "string",
                                        "title_en": "string",
                                        "content_ru": "string",
                                        "content_kk": "string",
                                        "content_en": "string",
                                        "tags": [
                                            "string"
                                        ],
                                        "start_at": "string",
                                        "created_at": "string",
                                        "updated_at": "string",
                                        "imgsrc": "string",
                                        "delete": 0,
                                        "title": "string",
                                        "content": "string",
                                        "author": {
                                            "id": 0,
                                            "name": "string",
                                            "email": "string"
                                        }
                                    }],
                                    "meta": {
                                        "size": 0,
                                        "perpage": 0,
                                        "page": 0
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": ["Мероприятия"],
                "summary": "Создать мероприятие",
                "description": "Создаёт статью для сайта. Тело `multipart/form-data`",
                "security": [{ "api_key": [] }],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "title_ru": { "type": "string" },
                                    "title_kk": { "type": "string" },
                                    "title_en": { "type": "string" },
                                    "content_ru": { "type": "string" },
                                    "content_kk": { "type": "string" },
                                    "content_en": { "type": "string" },
                                    "start_at": { "type": "string" },
                                    "tags": { "type": "array", "items": { "type": "string" } },
                                    "photo": { "type": "string", "format": "binary" }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Создано",
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Created"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/event/{slug}": {
            "get": {
                "tags": ["Мероприятия"],
                "summary": "Получить мероприятие",
                "description": "Два режима работы: С авторизацией (больше информации), и без авторизации",
                "parameters": [
                    { "name": "Accept-Language", "in": "header", "required": true, "description": "Язык", "schema": { "enum": [ "kk", "ru" ] } },
                    { "name": "slug", "required": true, "description": "Получить статью по slug-у", "in": "path", "schema": { "type": "string"}}
                ],
                "responses": {
                    "200": {
                        "description": "Один элемент",
                        "content": {
                            "application/json": {
                                "example": {
                                    "id": 0,
                                    "slug": "string",
                                    "title_ru": "string",
                                    "title_kk": "string",
                                    "title_en": "string",
                                    "content_ru": "string",
                                    "content_kk": "string",
                                    "content_en": "string",
                                    "tags": [
                                        "string"
                                    ],
                                    "start_at": "string",
                                    "created_at": "string",
                                    "updated_at": "string",
                                    "imgsrc": "string",
                                    "delete": 0,
                                    "title": "string",
                                    "content": "string",
                                    "author": {
                                        "id": 0,
                                        "name": "string",
                                        "email": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": ["Мероприятия"],
                "summary": "Обновить мероприятие",
                "description": "Обновить статью на сайте. Тело `multipart/form-data`",
                "security": [{ "api_key": [] }],
                "parameters": [
                    { "name": "slug", "required": true, "description": "Получить статью по slug-у", "in": "path", "schema": { "type": "string" }}
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "title_ru": { "type": "string" },
                                    "title_kk": { "type": "string" },
                                    "title_en": { "type": "string" },
                                    "content_ru": { "type": "string" },
                                    "content_kk": { "type": "string" },
                                    "content_en": { "type": "string" },
                                    "start_at": { "type": "string" },
                                    "tags": { "type": "array", "items": { "type": "string" } },
                                    "photo": { "type": "string", "format": "binary" }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "202": {
                        "description": "Обновлено",
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Updated"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/event/{id}": {
            "delete": {
                "tags": ["Мероприятия"],
                "summary": "Архивировать мероприятие",
                "description": "",
                "security": [{ "api_key": [] }],
                "parameters": [
                    { "name": "id", "required": true, "in": "path", "schema": { "type": "string" }}
                ],
                "responses": {
                    "202": {
                        "description": "",
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Ok, post <id> delete"
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "tags": ["Мероприятия"],
                "summary": "Восстановить мероприятие",
                "description": "",
                "security": [{ "api_key": [] }],
                "parameters": [
                    { "name": "id", "required": true, "in": "path", "schema": { "type": "string" }}
                ],
                "responses": {
                    "202": {
                        "description": "",
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Ok, post <id> revert"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/price-list": {
            "get": {
                "tags": [ "Прайслист" ],
                "summary": "Получить Прайслист",
                "description": "Два режима работы: С авторизацией (отключено кэширование), и без авторизации",
                "parameters": [
                    { "name": "Accept-Language", "in": "header", "required": true, "description": "Язык", "schema": { "enum": [ "kk", "ru" ] } }
                ],
                "responses": {
                    "200": {
                        "description": "Успешно",
                        "content": {
                            "application/json": {
                                "example": [
                                    {
                                        "title": "group title",
                                        "prices": {
                                            "price-string": {
                                                "price": 0,
                                                "discount": 0,
                                                "tags": [ "string" ],
                                                "final_price": 0,
                                                "title": "price string"
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/price": {
            "get": {
                "tags": [ "Цена" ],
                "summary": "Получить цены",
                "description": "Два режима работы: С авторизацией (отключено кэширование), и без авторизации",
                "security": [{ "api_key": [] }],
                "parameters": [
                    { "name": "Accept-Language", "in": "header", "required": true, "description": "Язык", "schema": { "enum": [ "kk", "ru" ] } }
                ],
                "responses": {
                    "200": {
                        "description": "Успешно",
                        "content": {
                            "application/json": {
                                "example": {
                                    "items": [
                                        {
                                            "id": 0,
                                            "index_order": 0,
                                            "price": 0,
                                            "discount": 0,
                                            "tags": [ "string" ],
                                            "comment": "string",
                                            "delete": 0,
                                            "created_at": "string",
                                            "updated_at": "string",
                                            "title_ru": "string",
                                            "title_kk": "string",
                                            "price_group_id": 0,
                                            "final_price": 0,
                                            "title": "string",
                                            "group": {
                                                "id": 0,
                                                "title_ru": "string",
                                                "title_kk": "string",
                                                "order_index": 0,
                                                "delete": 0,
                                                "title": "string"
                                            },
                                            "author": {
                                                "id": 0,
                                                "name": "string",
                                                "email": "string"
                                            }
                                        }
                                    ],
                                    "meta": {
                                        "size": 2,
                                        "perpage": 15,
                                        "page": 1
                                    }
                                }
                                
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [ "Цена" ],
                "summary": "Указать цену",
                "security": [{ "api_key": [] }],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "group_id": { "type": "number" },
                                    "title_ru": { "type": "string" },
                                    "title_kk": { "type": "string" },
                                    "title_en": { "type": "string" },
                                    "price": { "type": "number" },
                                    "tags": { "type": "array", "items": { "type": "string" } },
                                    "discount": { "type": "number" },
                                    "comment": { "type": "string" }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Создано",
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Created"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/price/{id}": {
            "post": {
                "tags": [ "Цена" ],
                "summary": "Обновить цену",
                "security": [{ "api_key": [] }],
                "parameters": [
                    { "name": "id", "in": "path", "description": "", "schema": { "type": "number" }, "required": true }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "group_id": { "type": "number" },
                                    "title_ru": { "type": "string" },
                                    "title_kk": { "type": "string" },
                                    "title_en": { "type": "string" },
                                    "price": { "type": "number" },
                                    "tags": { "type": "array", "items": { "type": "string" } },
                                    "discount": { "type": "number" },
                                    "comment": { "type": "string" }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "202": {
                        "description": "Обновить",
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Updated"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [ "Цена" ],
                "summary": "Архивировать Прайс",
                "security": [{ "api_key": [] }],
                "parameters": [
                    { "name": "id", "in": "path", "description": "", "schema": { "type": "number" }, "required": true }
                ],
                "responses": {
                    "202": {
                        "description": "",
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Ok, price $id delete"
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "tags": [ "Цена" ],
                "summary": "Восстановить Прайс",
                "security": [{ "api_key": [] }],
                "parameters": [
                    { "name": "id", "in": "path", "description": "", "schema": { "type": "number" }, "required": true }
                ],
                "responses": {
                    "202": {
                        "description": "",
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Ok, price $id revert"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/price/batch": {
            "post": {
                "tags": [ "Группа для Прайслиста" ],
                "summary": "Создать Группу и Прайс к группе",
                "security": [{ "api_key": [] }],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "title_ru": { "type": "string" },
                                    "title_kk": { "type": "string" },
                                    "title_en": { "type": "string" },
                                    "prices": {
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "title_ru": { "type": "string" },
                                                "title_kk": { "type": "string" },
                                                "title_en": { "type": "string" },
                                                "price": { "type": "number" },
                                                "tags": { "type": "array", "items": { "type": "string" } },
                                                "discount": { "type": "number" },
                                                "comment": { "type": "string" }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Создано",
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Created"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/price-group": {
            "get": {
                "tags": [ "Группа для Прайслиста" ],
                "summary": "Получить Группы",
                "parameters": [
                    { "name": "page", "in": "query", "schema": { "default": 0, "type": "string" } },
                    { "name": "sort", "in": "query", "schema": { "type": "string", "enum": [ "-id", "id", "-created_at", "created_at", "title_ru", "-title_ru" ]} },
                    { "name": "childs", "in": "query", "description": "Отображение дочерних элементов", "schema": { "type": "string" } },
                    { "name": "title", "in": "query", "description": "Поиск по названию", "schema": { "type": "string" } }
                ],
                "security": [{ "api_key": [] }],
                "responses": {
                    "200": {
                        "description": "Успешно",
                        "content": {
                            "application/json": {
                                "example": {
                                    "items": [
                                        {
                                            "id": 0,
                                            "title_ru": "",
                                            "title_kk": "",
                                            "title_en": { "type": "string" },
                                            "order_index": 0,
                                            "delete": 0,
                                            "childs": {
                                                "name": { "data": "any" }
                                            }
                                        }
                                    ],
                                    "meta": {
                                        "size": 2,
                                        "perpage": 15,
                                        "page": 1
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [ "Группа для Прайслиста" ],
                "summary": "Создать группу",
                "security": [{ "api_key": [] }],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "title_ru": { "type": "string" },
                                    "title_kk": { "type": "string" },
                                    "order_index": { "type": "number" }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Создано",
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Created"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/price-group/{id}": {
            "post": {
                "tags": [ "Группа для Прайслиста" ],
                "summary": "Обновить группу",
                "security": [{ "api_key": [] }],
                "parameters": [
                    { "name": "id", "in": "path", "description": "", "schema": { "type": "number" }, "required": true }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "title_ru": { "type": "string" },
                                    "title_kk": { "type": "string" },
                                    "title_en": { "type": "string" },
                                    "order_index": { "type": "number" }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "202": {
                        "description": "Обновить",
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Updated"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [ "Группа для Прайслиста" ],
                "summary": "Архивировать группу",
                "security": [{ "api_key": [] }],
                "parameters": [
                    { "name": "id", "in": "path", "description": "", "schema": { "type": "number" }, "required": true }
                ],
                "responses": {
                    "202": {
                        "description": "",
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Ok, price group $id delete"
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "tags": [ "Группа для Прайслиста" ],
                "summary": "Восстановить группу",
                "security": [{ "api_key": [] }],
                "parameters": [
                    { "name": "id", "in": "path", "description": "", "schema": { "type": "number" }, "required": true }
                ],
                "responses": {
                    "202": {
                        "description": "",
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Ok, price group $id revert"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}